# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-12 16:20
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('datahub', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Folder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=255, verbose_name='label')),
                ('description', models.TextField(blank=True, verbose_name='description')),
                ('is_public', models.BooleanField(default=True, verbose_name='public')),
                ('date_created', models.DateTimeField(verbose_name='date created')),
                ('date_updated', models.DateTimeField(verbose_name='date updated')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='folders', to=settings.AUTH_USER_MODEL, verbose_name='owner')),
                ('tags', models.ManyToManyField(blank=True, to='datahub.Tag')),
            ],
            options={
                'ordering': ['-date_created'],
                'verbose_name': 'folder',
                'verbose_name_plural': 'folder',
            },
        ),
        migrations.AddField(
            model_name='document',
            name='folder',
            field=models.ManyToManyField(blank=True, to='datahub.Folder'),
        ),
    ]
