# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-13 14:15
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('datahub', '0002_auto_20160412_1820'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='folder',
            options={'ordering': ['-date_created'], 'verbose_name': 'folder', 'verbose_name_plural': 'folders'},
        ),
        migrations.RemoveField(
            model_name='folder',
            name='tags',
        ),
    ]
